### PR TITLE
Add inline annotations on GitHub Actions

### PR DESCRIPTION
**Pull request by jonchang**
This pull request will automatically enable inline annotations on audit issues if GitHub Actions is the detected continuous integration runner.

Example:

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can it also do this for `brew style`?

**Comment by jonchang** [comment]
This is gonna need more time in the oven. https://github.com/actions/toolkit/issues/305 is causing a lot of headaches for what seemed to be a straightforward change.

**Comment by MikeMcQuaid** [comment]
Resolving the merge conflicts here may be a nightmare. You might want to remake this from scratch.

Another option I was thinking about would be if we just make `brew audit` output these directly with e.g. https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message

**Comment by jonchang** [comment]
I don't have time to work on this right now unfortunately. I'll revisit this (probably in `brew audit`) when I'm less busy.

**Pull request closed without merging**
