### PR TITLE
test_bot: fix curl regression

### PR DESCRIPTION
**Pull request by Bo98**
```
Error: undefined method `CURL' for Homebrew::TestBot:Module
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:257:in `block (2 levels) in test_ci_upload'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:213:in `each'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:213:in `block in test_ci_upload'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:204:in `each'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:204:in `test_ci_upload'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:338:in `run!'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/cmd/test-bot.rb:81:in `test_bot'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Homebrew/brew.rb:103:in `<main>'
```

### CODE REVIEW

**Comment by Bo98** [comment]
I'll rerun all affected bottle upload jobs once merged.

**Comment by Bo98** [comment]
Just going to merge this immediately without review, soz.

I've verified locally that the secrets are safe at least.

**Comment by Bo98** [comment]
I think that's everything back to normal.

**Comment by iMichka** [comment]
Thanks. This part is hard not really tested, so I missed these important details. Sorry for the bug.

**Comment by Bo98** [comment]
Yeah, to be honest we should come up with a better way to test the test bot that's not [a dry run](https://github.com/Homebrew/homebrew-test-bot/blob/master/.github/workflows/tests.yml#L65).

**Comment by iMichka** [comment]
A revert is often fine on test-bot. Most changes are not urgent. If you look at the git history of this repo we have been live-testing it often, and reverted a lot of stuff.

**Pull request merged**
