### PR TITLE
azure/travis: update to xcode 10

### PR DESCRIPTION
**Pull request by commitay**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@commitay Why the close?

**Comment by commitay** [comment]
When I opened this I'd forgotten about Azure. They have Xcode 10 support but
`vmImage: xcode10-macos10.13` doesn't seem to work.

**Comment by MikeMcQuaid** [comment]
@commitay Do you have a failed log or similar you can share? Would be good to report that to MS.

**Comment by commitay** [comment]
https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=484&view=results

screen shot 2018-10-11 at 23 11 37

**Comment by MikeMcQuaid** [comment]
@commitay Thanks! Looks like there may be an Xcode 10 in the image we're currently using if we `xcode-select --switch` to it?

**Comment by commitay** [comment]
Seems to be working.

**Comment by MikeMcQuaid** [comment]
@commitay 👍 merge when ready (and open a similar PR for Homebrew/brew, thanks 🙇)

**Pull request merged**
