### PR TITLE
Revert "formulae_dependents: prune build deps when linking test deps"

### PR DESCRIPTION
**Pull request by carlocab**
This still doesn't fix the overzealous linking of formulae,
unfortunately. See Homebrew/homebrew-core#89621.

This reverts commit 85aaf199e2b236becd6c1286886fe3a59581f329.

### CODE REVIEW

**Comment by carlocab** [comment]
Sorry @FnControlOption, this didn't work. Thanks anyway!

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by carlocab** [comment]
Btw, @MikeMcQuaid, I'm not able to merge this (merge button is greyed out), but this (and #717) should be ready to go.

**Comment by MikeMcQuaid** [comment]
@carlocab should be fixed now, can you try again?

**Comment by carlocab** [comment]
Yep, merge button is green. Thanks!

> This probably would have worked if we did:
> 
> ```ruby
> dependent.recursive_dependencies do |dep_dependent, dependency|
>   Dependency.prune if dependency.build? && !dependency.test?
>   Dependency.prune if dependency.test? && dep_dependent != dependent
> ```

While this does fix the linked CI error, this does not seem to fix the original error we wanted to fix. Our test cases are `mathblibtools` and `phplint`. We need: `coreutils` to be linked when `dependent` is `mathlibtools`, and we need `httpd` to be _not_ linked when `dependent` is `phplint`. We get the latter but not the former:

```ruby
# linked.rb
require 'formula'

def puts_linked(dependent)
  dependent.recursive_dependencies do |dep_dependent, dependency|
    Dependency.prune if dependency.build? && !dependency.test?
    Dependency.prune if dependency.test? && dep_dependent != dependency

    dependency_f = dependency.to_formula
    Dependency.skip if dependency_f.keg_only?
    puts dependency_f.full_name
  end
end

puts ARGV[0]
puts_linked(Formula[ARGV[0]])
```

Here's what we get:
```
❯ brew ruby linked.rb "mathlibtools" | rg -q 'coreutils'; echo $?
1
❯ brew ruby linked.rb "phplint" | rg -q 'httpd'; echo $?
1
```

**Comment by Bo98** [comment]
Your `!=` condition is wrong. It should be `dep_dependent != dependent`.

**Comment by carlocab** [comment]
And here I thought I double-checked that... and yes, it works:
```
```

**Comment by Bo98** [comment]
> This seems to have a bunch of duplicates

You should take the return value rather than treat this like `.each`.

**Comment by carlocab** [comment]
So we'd need to move the `brew link` step outside the block too. Ok, let's see...

**Comment by carlocab** [comment]
Not sure what I'm doing wrong here:
```ruby
# linked.rb
require 'formula'

def linked(dependent)
  dependent.recursive_dependencies do |dep_dependent, dependency|
    Dependency.prune if dependency.build? && !dependency.test?
    Dependency.prune if dependency.test? && dep_dependent != dependency

    dependency_f = dependency.to_formula
    Dependency.skip if dependency_f.keg_only?
  end
end

puts linked(Formula[ARGV[0]]).map(&:to_s)
```
❯ brew ruby linked.rb "mathlibtools"
gdbm
mpdecimal
ca-certificates
xz
six
```
No more `coreutils`.

```

**Pull request merged**
