### PR TITLE
Revert "brew-test-bot: Enable RPATH rewriting during tests"

### PR DESCRIPTION
**Pull request by woodruffw**
This reverts commit 30ba31514b4299735582b339cd99262bd8ed208f.

cc @scpeters

### CODE REVIEW

**Comment by scpeters** [comment]
here's the log from one of my builds that failed:

* https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/204/label=osx_highsierra/console

I can run that job with a custom test-bot repository and branch if that's helpful

**Comment by woodruffw** [comment]
> I can run that job with a custom test-bot repository and branch if that's helpful

It would be, yeah! Would it also be possible to get one or more of the built dylibs? I'd like to see if they do indeed have lazy install names.

**Comment by scpeters** [comment]
So I saw some error messages during that build, but only from bottles that had already been built and were being installed as dependencies.

For example, jasper had a `Error: Failed to fix install linkage`:

~~~
==> Installing osrf/simulation/ignition-gui1 dependency: jasper
==> Downloading https://homebrew.bintray.com/bottles/jasper-2.0.16.high_sierra.bottle.tar.gz
Already downloaded: /Users/jenkins/Library/Caches/Homebrew/downloads/e9b256f894523b56000afc9125ebe7c721ff60ed8ff12396ba2d9f4abe52a360--jasper-2.0.16.high_sierra.bottle.tar.gz
==> Pouring jasper-2.0.16.high_sierra.bottle.tar.gz
Error: Failed to fix install linkage
The formula built, but you may encounter issues using it or linking other
formula against it.
==> Summary
/usr/local/Cellar/jasper/2.0.16: 40 files, 1.4MB
~~~

There were several others with `Warning: Could not find library @rpath/libname for /usr/local/Cellar/...libname`:

~~~
==> Installing osrf/simulation/ignition-gui1 dependency: ignition-common3
==> Downloading https://osrf-distributions.s3.amazonaws.com/bottles-simulation/ignition-common3-3.0.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/jenkins/Library/Caches/Homebrew/downloads/588f41a86e3c31cd0f5592ec85c772d4f2558259ef011fab9196e5d62d0937ce--ignition-common3-3.0.0.high_sierra.bottle.tar.gz
==> Pouring ignition-common3-3.0.0.high_sierra.bottle.tar.gz
Warning: Could not find library @rpath/libignition-common3.3.dylib for /usr/local/Cellar/ignition-common3/3.0.0/lib/libignition-common3-av.3.0.0.dylib
Warning: Could not find library @rpath/libignition-common3.3.dylib for /usr/local/Cellar/ignition-common3/3.0.0/lib/libignition-common3-events.3.0.0.dylib
Warning: Could not find library @rpath/libignition-common3.3.dylib for /usr/local/Cellar/ignition-common3/3.0.0/lib/libignition-common3-graphics.3.0.0.dylib
Warning: Could not find library @rpath/libignition-common3.3.dylib for /usr/local/Cellar/ignition-common3/3.0.0/lib/libignition-common3-profiler.3.0.0.dylib
/usr/local/Cellar/ignition-common3/3.0.0: 168 files, 1.5MB
~~~

~~~
==> Installing osrf/simulation/ignition-gui1 dependency: ignition-plugin1
==> Downloading https://osrf-distributions.s3.amazonaws.com/bottles-simulation/ignition-plugin1-1.0.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/jenkins/Library/Caches/Homebrew/downloads/1f88f6ed02aa9913b9143f3871d900d35207b95fcfbf997044ded375631b5ed2--ignition-plugin1-1.0.0.high_sierra.bottle.tar.gz
==> Pouring ignition-plugin1-1.0.0.high_sierra.bottle.tar.gz
Warning: Could not find library @rpath/libignition-plugin1.1.dylib for /usr/local/Cellar/ignition-plugin1/1.0.0/lib/libignition-plugin1-loader.1.0.0.dylib
/usr/local/Cellar/ignition-plugin1/1.0.0: 53 files, 331.4KB
~~~

~~~
==> Installing osrf/simulation/ignition-gui1 dependency: tbb
==> Downloading https://homebrew.bintray.com/bottles/tbb-2019_U3_1.high_sierra.bottle.tar.gz
Already downloaded: /Users/jenkins/Library/Caches/Homebrew/downloads/5636a020857f792bb34c8d14d074f0768e53547fa90146afad95c48f9ffdf647--tbb-2019_U3_1.high_sierra.bottle.tar.gz
==> Pouring tbb-2019_U3_1.high_sierra.bottle.tar.gz
Warning: Could not find library @rpath/libtbbmalloc.dylib for /usr/local/Cellar/tbb/2019_U3_1/lib/libtbbmalloc_proxy.dylib
Warning: Could not find library @rpath/libtbb.dylib for /usr/local/Cellar/tbb/2019_U3_1/lib/python3.7/site-packages/tbb/_api.cpython-37m-darwin.so
/usr/local/Cellar/tbb/2019_U3_1: 134 files, 2.7MB
~~~

Are any of those errors interesting to you? Those bottles are all published and the URL's are in the console message.

**Comment by MikeMcQuaid** [comment]
Suggestion: instead of setting it in `brew test-bot` set it in the Jenkins configuration instead where it can be trivially added/removed without code changes.

**Comment by woodruffw** [comment]
> Suggestion: instead of setting it in `brew test-bot` set it in the Jenkins configuration instead where it can be trivially added/removed without code changes.

Yep, I'll do that for future tests. Thanks!

**Pull request merged**
