### PR TITLE
lib/tests/formulae: install `ca-certificates` if needed

### PR DESCRIPTION
**Pull request by carlocab**
This is needed to fix Homebrew/core CI. See Homebrew/brew#12167.

### CODE REVIEW

**Comment by carlocab** [comment]
Just for extra context, we need this to fix SSL cert errors like [this one](https://github.com/Homebrew/homebrew-core/pull/86321/checks?check_run_id=3786493923#step:7:30) from Homebrew/homebrew-core#86321, since we reverted 28bed81e8552f3039211bdb33c21d1ee2c9a5ffd in b6de336902f37c73ebe70b9581913f86306b7b99.

**Review by dawidd6 — APPROVED** [review]

**Review by Rylan12 — APPROVED** [review]
Why isn't this being done by the `brew install ca-certificates` line in [`update.sh`](https://github.com/Homebrew/brew/blob/1952d27ba295cdb9e560c464b2631c1d80549408/Library/Homebrew/cmd/update.sh#L384)?

**Comment by carlocab** [comment]
> Why isn't this being done by the `brew install ca-certificates` line in [`update.sh`](https://github.com/Homebrew/brew/blob/1952d27ba295cdb9e560c464b2631c1d80549408/Library/Homebrew/cmd/update.sh#L384)?

`test-bot` never actually runs `brew update`, I think.

**Comment by Rylan12** [comment]
Thanks, @carlocab!

**Pull request merged**
