### PR TITLE
Revert "Fix detection of modified formulae on Azure"

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Reverts Homebrew/homebrew-test-bot#255

### CODE REVIEW

**Comment by ladislas** [comment]
something's wrong? :(

**Comment by MikeMcQuaid** [comment]
@ladislas See https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=9239&view=logs https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=9236&view=logs&jobId=a8f4870e-143f-5768-9e41-e85853590278&taskId=ceeb95c1-eed2-58c1-5545-3d8432b2d3ea&lineStart=133&lineEnd=134&colStart=1&colEnd=1  https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=9236&view=logs

**Comment by sjackman** [comment]
```
Error: no implicit conversion of nil into String
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:416:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:416:in `download'
```
https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=9239&view=logs&jobId=50a69d0a-7972-5459-cdae-135ee6ebe312&taskId=10352565-4cc8-5984-5886-e59588f0792d&lineStart=23&lineEnd=24&colStart=1&colEnd=1

My best guess is that it's failing if `SYSTEM_PULLREQUEST_SOURCEBRANCH` is not defined.

I suggest removing line 416
```ruby
system("git", "-C", @repository, "checkout", ENV["SYSTEM_PULLREQUEST_SOURCEBRANCH"])
```
and trying this PR without that line.

**Comment by ladislas** [comment]
@sjackman I've reached the same conclusion.

removing the line 416 brings back my issue as seen here: https://dev.azure.com/ladisonline/homebrew-hello-world/_build/results?buildId=310

- the diff of brew-test-bot.rb: https://dev.azure.com/ladisonline/homebrew-hello-world/_build/results?buildId=310&view=logs&jobId=f720af0a-4aeb-5402-58ab-558049540efe&taskId=ae4f81c5-5d17-5446-4376-d7d8fd046541&lineStart=19&lineEnd=33&colStart=1&colEnd=32
- the "nothing happens as we can't calculate the start sha1": https://dev.azure.com/ladisonline/homebrew-hello-world/_build/results?buildId=310&view=logs&jobId=f720af0a-4aeb-5402-58ab-558049540efe&taskId=b37980cf-3630-5342-dd54-7700c0688f56&lineStart=91&lineEnd=92&colStart=1&colEnd=40

**Comment by ladislas** [comment]
What about checking for 'SYSTEM_PULLREQUEST_SOURCEBRANCH' and if it exists, doing the checkout?

**Comment by MikeMcQuaid** [comment]
That seems sensible.

**Comment by sjackman** [comment]
I had previously suggested
```ruby
system("git", "-C", @repository, "fetch", "origin", ENV["SYSTEM_PULLREQUEST_TARGETBRANCH"])
```
immediately before the `git rev-parse`, but I'm not sure that's actually the problem.

```
ladislas/hello-world origin/master 8a9f608 (reactivate dev test bot)
ladislas/hello-world HEAD 7f1ac7e (Merge 6afbe2ed6e479a0e8e5603478b49ab3d745bcba1 into 8a9f6084c0dfe4f85a03bd169e7032a3582bdef5)
```
The last commit on `HEAD` looks like a merge commit. What's the last commit on the PR that you're trying to merge?

I don't see an error message in this build log. What line of the build log do you think is the indication of trouble? What do you expect to see, and what are you seeing?

**Comment by sjackman** [comment]
I've found it similar difficult to troubleshoot `test-bot` when `diff_start_sha1` and `diff_end_sha1` are not getting the values that I think they should. I don't see in `test-bot` that their value is printed unambiguously and clearly in the build log. I think it would help to print the value of these two variables in the build log. Something like:
```
ohai "Testing commits #{diff_start_sha1} to #{diff_end_sha1}`
```

**Comment by MikeMcQuaid** [comment]
> I think it would help to print the value of these two variables in the build log.

Good idea 👍

**Comment by iMichka** [comment]
I had the same problem debugging that part once. And I never got the azure thing to work. Thanks to try to fix this.

I think adding that line in the log output would help a little bit in some cases.

**Comment by ladislas** [comment]
Big +1 for `ohai`. I would also add some log on the added/modified/deleted formulae, what do you think?

I've tried the following, it works (as expected) and adds a check for `SYSTEM_PULLREQUEST_SOURCEBRANCH`

https://github.com/ladislas/homebrew-test-bot/commit/7e3ac1f7b569ba4db458997f9f9d79f09a9f8783

> I had previously suggested

@sjackman like this?

```ruby
system("git", "-C", @repository, "fetch", "origin", ENV["SYSTEM_PULLREQUEST_TARGETBRANCH"])
diff_start_sha1 =
  Utils.popen_read("git", "-C", @repository, "rev-parse",
                          "--short",
                          "origin/#{ENV["SYSTEM_PULLREQUEST_TARGETBRANCH"]}").strip
```

If so, I'll try it right now and let you know.

> The last commit on HEAD looks like a merge commit. What's the last commit on the PR that you're trying to merge?

@sjackman this is the merge commit generated by Azure Pipelines that you can find here: https://dev.azure.com/ladisonline/homebrew-hello-world/_build/results?buildId=311&view=logs&jobId=f720af0a-4aeb-5402-58ab-558049540efe&taskId=447c4b16-b77a-5636-6a60-8b487cc3bc78&lineStart=178&lineEnd=179&colStart=1&colEnd=116 -- that's the one I'm trying to escape from by checking out the target branch (in my case `master`

> I don't see an error message in this build log. What line of the build log do you think is the indication of trouble? What do you expect to see, and what are you seeing?

As it doesn't find the modified formula, it stops running after that: https://dev.azure.com/ladisonline/homebrew-hello-world/_build/results?buildId=310&view=logs&jobId=f720af0a-4aeb-5402-58ab-558049540efe&taskId=b37980cf-3630-5342-dd54-7700c0688f56&lineStart=91&lineEnd=92&colStart=1&colEnd=40 -- so no bottles are created and the "copy bottles & json files" steps then fails with `cp: *.bottle.*: No such file or directory` https://dev.azure.com/ladisonline/homebrew-hello-world/_build/results?buildId=310&view=logs&jobId=f720af0a-4aeb-5402-58ab-558049540efe&taskId=f2fcdc02-a777-5bb8-8971-48a1deaa6619&lineStart=11&lineEnd=16&colStart=1&colEnd=47

> I had the same problem debugging that part once. And I never got the azure thing to work. Thanks to try to fix this.

@iMichka I think I'm getting close :)

@MikeMcQuaid in order to test things without breaking production code in the other pipelines, is there some "staging" environment that could run in parallel and where we would try PR like this one?

**Comment by ladislas** [comment]
@sjackman no it did not work :( https://dev.azure.com/ladisonline/homebrew-hello-world/_build/results?buildId=312&view=logs&jobId=f720af0a-4aeb-5402-58ab-558049540efe&taskId=ae4f81c5-5d17-5446-4376-d7d8fd046541&lineStart=17&lineEnd=41&colStart=1&colEnd=27

**Comment by sjackman** [comment]
> in order to test things without breaking production code in the other pipelines, is there some "staging" environment that could run in parallel and where we would try PR like this one?

I've never done it, but you could try modifying the file `Formula/testbottest.rb` (add a comment or something) in this same PR to test that branch of code.

**Comment by sjackman** [comment]
I believe that checking out `SYSTEM_PULLREQUEST_TARGETBRANCH` is not addressing the real problem. CircleCI uses
```ruby
      elsif ENV["CIRCLE_SHA1"]
        diff_start_sha1 =
          Utils.popen_read("git", "-C", @repository, "rev-parse",
                                  "--short", "origin/master").strip
```
and I know that code works.

Azure has (or will have again)…
```ruby
      elsif ENV["SYSTEM_PULLREQUEST_TARGETBRANCH"] && ENV["BUILD_SOURCEVERSION"]
        diff_start_sha1 =
          Utils.popen_read("git", "-C", @repository, "rev-parse",
                                  "--short",
                                  "origin/#{ENV["SYSTEM_PULLREQUEST_TARGETBRANCH"]).strip}"
        diff_end_sha1 = current_sha1
```

Two questions…
1. Are we sure that `SYSTEM_PULLREQUEST_TARGETBRANCH` is defined?
2. Are we sure that its value is `master`?

**Comment by ladislas** [comment]
@sjackman from Azure doc: [link](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)

| Variable | Description |
-- | --
|System.PullRequest.TargetBranch | The branch that is the target of a pull request. For example: refs/heads/master. This variable is initialized only if the build ran because of a Git PR affected by a branch policy.

> 1. Are we sure that SYSTEM_PULLREQUEST_TARGETBRANCH is defined?

If the build is from a PR, yes

> 2. Are we sure that its value is `master`?

No, it will be the branch targeted by the PR.

I'll try the Circle approach just to make sure 👓

**Comment by ladislas** [comment]
> I'll try the Circle approach just to make sure

Nope... https://dev.azure.com/ladisonline/homebrew-hello-world/_build/results?buildId=313

**Comment by sjackman** [comment]
Where is the PR that you are using for testing this code?
Please open a PR to add `ohai "Testing commits #{diff_start_sha1} to #{diff_end_sha1}`

**Comment by ladislas** [comment]
> Where is the PR that you are using for testing this code?

working on a personal fork, I have not made a PR yet to not flood you with notifications while I test different things.

> Please open a PR to add ohai "Testing commits #{diff_start_sha1} to #{diff_end_sha1}

Will do!

**Comment by sjackman** [comment]
>> Where is the PR that you are using for testing this code?

> working on a personal fork, I have not made a PR yet to not flood you with notifications while I test different things.

Could you please point me to the PR on GitHub in your personal fork?

**Comment by sjackman** [comment]
>> Please open a PR to add ohai "Testing commits #{diff_start_sha1} to #{diff_end_sha1}

> Will do!

Great!

**Comment by ladislas** [comment]
> Could you please point me to the PR on GitHub in your personal fork?

The PR being tested is this one: https://github.com/ladislas/homebrew-hello-world/pull/13
My personal fork of brew test-bot is this one: https://github.com/ladislas/homebrew-test-bot/ (on `master` as calling `brew test-bot` checks out master in the `homebrew/test-bot` tap)

**Comment by ladislas** [comment]
@MikeMcQuaid @sjackman what does the following do?

https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L449-L451

**Comment by sjackman** [comment]
```ruby
  diff_start_sha1 =
    Utils.popen_read("git", "-C", @repository, "merge-base",
                            diff_start_sha1, diff_end_sha1).strip
```
It sets `diff_start_sha1` to the most recent common ancestor of `diff_start_sha1` and `diff_end_sha1`. That is to say the most recent parent commit of both commits.

**Comment by sjackman** [comment]
Its relevant when the PR is not rebased onto the current `origin/master`.

**Comment by ladislas** [comment]
Thanks a lot! :)

**Comment by sjackman** [comment]
Try adding these lines to your `azure-pipelines.yml`
```sh
        set -ex
        if [[ -n "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" ]]; then
          git fetch origin "master:master" "pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/head:pr"
          git checkout pr
        fi
```
https://github.com/brewsci/homebrew-bio/blob/a52661e1a753d458e4a8795b43ab159e1cb8add4/azure-pipelines.yml#L7-L12

**Comment by sjackman** [comment]
If that works, we can consider adding those lines to `brew test-bot`.

**Comment by sjackman** [comment]
I just remembered one thing about Azure that's different than some other CI systems. The default commit that's checked out is `pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/merge` rather than perhaps the more typical `pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/head`. I believe that breaks `brew test-bot`.

**Comment by ladislas** [comment]
@sjackman your suggestion works! :) 🎉

**Comment by MikeMcQuaid** [comment]
> The default commit that's checked out is `pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/merge` rather than perhaps the more typical `pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/head`. I believe that breaks `brew test-bot`.

Travis and Jenkins (in some configurations) both did that too.

> > 1. Are we sure that SYSTEM_PULLREQUEST_TARGETBRANCH is defined?
> 
> If the build is from a PR, yes

To be explicit: need to ensure this code works even when the build is not from a PR.

**Comment by ladislas** [comment]
> To be explicit: need to ensure this code works even when the build is not from a PR.

So when we are just building a branch like `master` to make sure it still works?

**Comment by MikeMcQuaid** [comment]
Yes.

**Comment by ladislas** [comment]
@MikeMcQuaid @sjackman quick question: what does the following do and when is it supposed to run? https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L531-L542

(pointed out by @MikeMcQuaid here: https://github.com/Homebrew/homebrew-test-bot/pull/258#discussion_r283655711)

```ruby
      if @tap
        tap_origin_master_revision = Utils.popen_read(
          "git", "-C", @tap.path.to_s,
                 "log", "-1", "--format=%h (%s)", "origin/master"
        ).strip
        puts "#{@tap} origin/master #{tap_origin_master_revision}"
        tap_revision = Utils.popen_read(
          "git", "-C", @tap.path.to_s,
                 "log", "-1", "--format=%h (%s)"
        ).strip
        puts "#{@tap} HEAD #{tap_revision}"
      end
```

I'm asking because I'm working on a tap and not on `brew` or `homebrew-core`. Are all three supposed to take the same path through `brew test-bot` and if not where do they diverge?

**Comment by MikeMcQuaid** [comment]
That prints out the value of `origin/master` and `HEAD` (the currently checked out revision) for the current tap. Above that it'll also print out the values of `HEAD` for Homebrew/brew and Homebrew/homebrew-core.

**Comment by sjackman** [comment]
I believe these `origin/master` and `HEAD` should be the same values as `diff_start_sha1` and `diff_end_sha1` if the PR is up-to-date and all is working as intended.

**Comment by ladislas** [comment]
As previously said, this suggestion by @sjackman (https://github.com/Homebrew/homebrew-test-bot/pull/256#issuecomment-491990986) solves the detection issue.

Should I make a new PR adding this to brew test-bot or is it better to keep in documentation for users to add it to their pipelines?

**Comment by sjackman** [comment]
I've opened PR https://github.com/Homebrew/homebrew-test-bot/pull/261 to fix this issue for other taps.

**Comment by sjackman** [comment]
I also merged PR https://github.com/Homebrew/homebrew-test-bot/pull/260 to fix this issue for Homebrew/test-bot.

**Comment by ladislas** [comment]
Thanks @sjackman! It looks promising! :)

**Pull request merged**
