### PR TITLE
Dockerfile: base on latest master build

### PR DESCRIPTION
**Pull request by dawidd6**
https://github.com/Homebrew/homebrew-test-bot/pull/422

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@sjackman @dawidd6 Looks like something messed up with `brew doctor` (due to uncommitted files) in the Docker images. If we don't already I reckon we should probably run it in the CI jobs that generate the docker images?

**Comment by dawidd6** [comment]
Hmm, somehow `brew` is outdated in the image:

```
==> Using Homebrew/brew 2.2.16-81-g95a821722 (Merge pull request #7588 from maxim-belkin/glibc-minimum-version)

==> Running Setup#run!
==> brew config
HOMEBREW_VERSION: 2.2.16-81-g95a8217
ORIGIN: https://github.com/Homebrew/brew
HEAD: 95a8217223c49d08c1e002f5ea551e0c6be9f1de
Last commit: 3 weeks ago
...
```

**Comment by MikeMcQuaid** [comment]
Weird. Could it be the Docker image upload is broken?

**Comment by sjackman** [comment]
```
$ docker pull homebrew/ubuntu16.04:master
Digest: sha256:f21b739f964ccee92730f7000782d324f4dd352393f7b3a2901fcee4a2c69c1c
Status: Downloaded newer image for homebrew/ubuntu16.04:master
docker.io/homebrew/ubuntu16.04:master
$ docker run -it --rm homebrew/ubuntu16.04:master brew --version
Homebrew 2.3.0-71-g3a7213c
Homebrew/linuxbrew-core (git revision c40b6; last commit 2020-06-09)
```
Looks good to me?

**Comment by sjackman** [comment]
```console
$ docker build -t brew .
Digest: sha256:d73dc1e493c5c35ba7e90b6c301e660f3d2390913a6997c422281e6ae3e4c981
Status: Downloaded newer image for homebrew/ubuntu16.04:master
```
https://github.com/Homebrew/homebrew-test-bot/pull/424/checks?check_run_id=752971317#step:10:40

```
$ docker run -it --rm 'homebrew/ubuntu16.04@sha256:d73dc1e493c5c35ba7e90b6c301e660f3d2390913a6997c422281e6ae3e4c981' brew --version
Homebrew 2.3.0-67-gd07d220
Homebrew/linuxbrew-core (git revision 509ee; last commit 2020-06-07)
```
The base Docker image downloaded in the step `Build Docker image` had Homebrew version 2.3.0-67.

https://github.com/Homebrew/homebrew-test-bot/blob/0cc362926b37f688b0a614e452ebc91dcc71f1d2/.github/workflows/tests.yml#L86

Are we sure that the environment variable `RUNNER_OS` is set?

**Comment by MikeMcQuaid** [comment]
> Are we sure that the environment variable `RUNNER_OS` is set?

Yup: https://github.com/Homebrew/homebrew-test-bot/pull/424/checks?check_run_id=756953989#step:11:11

> ==> git -C /home/linuxbrew/.linuxbrew/Homebrew checkout -f master
> ==> git -C /home/linuxbrew/.linuxbrew/Homebrew reset --hard origin/master
> ==> git -C /home/linuxbrew/.linuxbrew/Homebrew clean -ff -dx

could it be that `origin/master` isn't up to date?

**Comment by MikeMcQuaid** [comment]
@sjackman @dawidd6 any other thoughts?

**Comment by sjackman** [comment]
> could it be that `origin/master` isn't up to date?

You get a gold star! 🌟

```console
$ docker run --rm homebrew/ubuntu16.04:master git -C /home/linuxbrew/.linuxbrew/Homebrew describe --tags origin/master master
2.3.0-35-g0af7a28fb
2.4.0-10-gc120b6120
```

**Comment by MikeMcQuaid** [comment]
@sjackman Cool, hopefully fixed by https://github.com/Homebrew/brew/pull/7731.

**Comment by MikeMcQuaid** [comment]
Nice, thanks @dawidd6!

**Pull request merged**
