### PR TITLE
Azure: Checkout pull/x/head rather than pull/x/merge

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Azure leaves you in detached head state with `pull/261/merge` checked out by default:
```console
$ git branch
* (HEAD detached at pull/261/merge)
```

**Comment by MikeMcQuaid** [comment]
> Azure leaves you in detached head state with `pull/261/merge` checked out by default:

Can you elaborate on what/why this is a problem? Thanks!

**Comment by sjackman** [comment]
The usual PR workflow of Homebrew does not include merge commits.
The usual PR workflow of Homebrew/linuxbrew-core uses merge commits when it's merging Homebrew-core into Linuxbrew-core. Seeing `HEAD` as a merge commit triggers special behaviour.
See PR https://github.com/Homebrew/homebrew-test-bot/pull/236
https://github.com/Homebrew/homebrew-test-bot/blob/ca01e464afe07d7028265254f01e55b4a7d0cf32/cmd/brew-test-bot.rb#L551-L554

**Comment by MikeMcQuaid** [comment]
> The usual PR workflow of Homebrew does not include merge commits.

It does for Homebrew/brew, this tap and external taps. Travis CI and Jenkins pipelines also default to checking out merge commits.

> The usual PR workflow of Homebrew/linuxbrew-core uses merge commits when it's merging Homebrew-core into Linuxbrew-core. Seeing `HEAD` as a merge commit triggers special behaviour.

I think I'd like to see that special-cased to just that tap by default with an optional `brew test-bot --special-merge-commit-behaviour` or something flag.

**Comment by MikeMcQuaid** [comment]
A notable issue with testing `head` rather than `merge` is it doesn't account for changes in `master` that may break things.

**Comment by MikeMcQuaid** [comment]
Rerunning CI so the https://github.com/Homebrew/homebrew-test-bot/pull/258 results can be viewed.

**Comment by ladislas** [comment]
I can't see the output of #258 on Linux :\

**Comment by MikeMcQuaid** [comment]
Heh, I think that demonstrates my point: it won't display it until it's rebased on `master` (which isn't what we want as default behaviour).

**Comment by ladislas** [comment]
but it is on macOS 😁 https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=9549&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=00f564b5-c6ae-5329-43c9-96bc79a72ec9&lineStart=46&lineEnd=50&colStart=1&colEnd=26

**Comment by sjackman** [comment]
>> The usual PR workflow of Homebrew does not include merge commits.

> It does for Homebrew/brew, this tap and external taps. Travis CI and Jenkins pipelines also default to checking out merge commits.

I misspoke. I meant that the PR itself does not include merge commits. The merge commit is created on `master`.

>> The usual PR workflow of Homebrew/linuxbrew-core uses merge commits when it's merging Homebrew-core into Linuxbrew-core. Seeing HEAD as a merge commit triggers special behaviour.

> I think I'd like to see that special-cased to just that tap by default with an optional brew test-bot --special-merge-commit-behaviour or something flag.

Agreed.

**Comment by sjackman** [comment]
> > The usual PR workflow of Homebrew does not include merge commits.

> Travis CI and Jenkins pipelines also default to checking out merge commits.

I doubt that's actually the case, because if it were, it would trigger the merge commit behaviour, and the PR would not be tested normally.

**Comment by sjackman** [comment]
On TravisCI and Jenkins, isn't the PR rebase onto origin/master by `brew test-bot` by applying the GitHub `…/pull/1234.patch` using `git am`? That's different than checkout out the merge commit `pull/1234/merge` that's created by GitHub, though it achieves a similar result.

**Comment by MikeMcQuaid** [comment]
It is the case: https://docs.travis-ci.com/user/pull-requests/#how-pull-requests-are-built

For Travis CI different variables are used for detecting the changes. That should be sufficient rather than checking out different commits.

**Comment by sjackman** [comment]
> Travis CI builds a pull request when it is first opened, and whenever commits are added to the pull request. Rather than build the commits that have been pushed to the branch the pull request is from, we build the merge between the source branch and the upstream branch.

https://docs.travis-ci.com/user/pull-requests/#how-pull-requests-are-built

> I think I'd like to see that special-cased to just that tap by default with an optional brew test-bot --special-merge-commit-behaviour or something flag.

This change is the better fix.

**Comment by MikeMcQuaid** [comment]
> On TravisCI and Jenkins, isn't the PR rebase onto origin/master by `brew test-bot` by applying the GitHub `…/pull/1234.patch` using `git am`?

No. See the use of `--no-pull` now in every CI provider case except `jenkins_pipeline_pr`. When we move from Jenkins to Azure for Homebrew/homebrew-core we will likely remove all the `--no-pull` logic in favour of making that the default everywhere.

**Comment by sjackman** [comment]
I think we can close this PR in favour of a special `brew test-bot --special-merge-commit-behaviour-or-something` flag for Homebrew/linuxbrew-core.

**Comment by MikeMcQuaid** [comment]
@sjackman Sounds good 👍

**Pull request closed without merging**
