### PR TITLE
Pass commit range to audit.

### PR DESCRIPTION
**Pull request by reitermarkus**
This passes the commit range of a PR to `audit`, used for the new check in https://github.com/Homebrew/brew/pull/2601.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Instead I'd rather we used the `FormulaVersions` class for this rather than modify `brew test-bot`.

**Comment by reitermarkus** [comment]
We'll still need to know the commit range of a PR when using `FormulaVersions`, don't we?

**Comment by MikeMcQuaid** [comment]
I'm not sure I understand why we would. We can detect `revision` and `version_scheme` changes without it so we should be able to do the same with a checksum.

**Comment by reitermarkus** [comment]
Figured it out.

**Pull request closed without merging**
