### PR TITLE
Use Docker to test the current commit of the PR

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
+ /home/linuxbrew/.linuxbrew/bin/brew test-bot
Homebrew/homebrew-test-bot 21bba24 (Use Docker to test the current commit of the PR)
ARGV: --verbose --ci-auto --no-pull --ci-pr --cleanup --test-default-formula --junit
```
https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=9445&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=45b31e99-b18c-506f-46cf-7d3a4d5140a9&lineStart=15&lineEnd=16&colStart=1&colEnd=1

Success!

**Comment by sjackman** [comment]
Homebrew/brew was already configured like this, so it should be fine.
See https://github.com/Homebrew/brew/blob/5a63de02237b7639796844888c57da5e03d4ec5f/Dockerfile#L28

Homebrew/test-bot is a special tap, because it's testing itself, so the working copy needs to be up-to-date before `brew test-bot` runs. We can improve `brew test-bot` so that other taps don't need this change.

**Comment by MikeMcQuaid** [comment]
> Homebrew/test-bot is a special tap, because it's testing itself, so the working copy needs to be up-to-date before `brew test-bot` runs. We can improve `brew test-bot` so that other taps don't need this change.

Gotcha, yeh, that'd be great.

**Comment by sjackman** [comment]
Opened PR #261 to fix this issue for other taps.

**Pull request merged**
