### PR TITLE
test: add --include-build whitelist.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Specify formulae where we want to test build dependants.

Prompted by discussion in https://github.com/Homebrew/homebrew-test-bot/pull/295. CC @Bo98 for thoughts.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
This will only test the tests and linkage of bottles. If we want to also test building from source: let me know.

**Comment by Bo98** [comment]
In these cases, it is the building from source that typically breaks rather than existing bottles.

**Comment by MikeMcQuaid** [comment]
@Bo98 Cool, check this out and let me know what you think.

**Comment by Bo98** [comment]
I think that should cover it.

I don't know if `go` necessarily needs to be on the list - it's updated often and I don't hear much about it, but perhaps I'm not the best person to ask about `go`. The others have definitely caused problems a few times.

**Comment by MikeMcQuaid** [comment]
Will check with @fxcoudert and @Homebrew/core: any things that should be added/removed from this list? Want to keep it really conservative for now (as it will massively increase PR times).

If they are too long I think we could do a random sample of a maximum number of dependents.

**Comment by SMillerDev** [comment]
If I understand correctly this will build anything that `depends_on "go" => :build` whenever go et all updates?

**Comment by MikeMcQuaid** [comment]
@SMillerDev Yes.

**Comment by fxcoudert** [comment]
This is a very good idea. Probably we want `rust` there too…

**Comment by MikeMcQuaid** [comment]
Thanks @fxcoudert. Added. Let's try this out...

**Comment by Bo98** [comment]
Time to start some fires. Rust 1.41.1 is up first: Homebrew/homebrew-core#50777.

OCaml 4.10.0 will follow when we decide whether to delete `camlp4` or create an `ocaml@4.08` especially for it: Homebrew/homebrew-core#49661. I updated the all remaining formulae that were depending on it today so there's no more dependents.

**Comment by zbeekman** [comment]
Sorry I'm late to the party... I'm not sure how to go about doing this, but Fortran packages (`depends_on :gcc # For gfortran`) can often break when a new major compiler version is released. This probably doesn't need changing here because the packages will link `libgfortran` (and other GCC runtime stuff...) so my guess is that anything that could accidentally break will require a revision bump anyway? But I might be missing something.

**Comment by Bo98** [comment]
Here's some results so far. Note that the build times will be a little shorter this time round since failuring formulae means less time building - particularly for `ghc` which often fails early due to strict version checks.

---

### Rust 1.14.1

Build times:
* Catalina: 14 hr
* Mojave: 13 hr
* High Sierra: 12 hr

Detected 10 formulae which fail to build from source plus 1 test failure. Documented at Homebrew/homebrew-core#50815.

High Sierra had additional failures like:

```
==> brew install --build-from-source graph-tool
==> FAILED
graph-tool: macOS Mojave or newer is required.
Error: An unsatisfied requirement failed this build.
```

Is it possible for homebrew-test-bot to detect this?

---

### GHC 8.8.3

Build times:
* Catalina: 11 hr
* Mojave: 9 hr 28 min
* High Sierra: 9 hr 20 min

Detected 14 formulae which fail to build from source. These are documented at https://github.com/Homebrew/homebrew-core/issues/48604#issuecomment-592593224.

**Comment by MikeMcQuaid** [comment]
Thanks @Bo98! Doesn't seem too bad, time wise.

> Is it possible for homebrew-test-bot to detect this?

It's possible but probably the correct solution (unless it's a `:build` dependency) is to add the same requirement to all dependants.

**Comment by Bo98** [comment]
Nothing depends on `graph-tool`. The way it was picked up was that it was testing building `librsvg` (which depends on `rust` at build time) and from that it built `graph-tool` from source (which depends `librsvg` at runtime). Requiring `librsvg` to depend on Mojave wouldn't be correct.

**Comment by MikeMcQuaid** [comment]
Ah gotcha. Yeh, it could be just skipped rather than failed.

**Pull request merged**
