### PR TITLE
Fix Linuxbrew repository location and core tap.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Apply changes from https://github.com/Homebrew/brew/pull/5448.

CC @jonchang @sjackman

### CODE REVIEW

**Comment by sjackman** [comment]
Failed with `Warning: Your Homebrew's prefix is not /usr/local.` on Linux. The default prefix should be `/home/linuxbrew/.linuxbrew` not` /usr/local`.
```
2018-12-29T12:40:11.2199349Z ==> brew doctor
…
2018-12-29T12:40:11.9527907Z Warning: Your Homebrew's prefix is not /usr/local.
…
2018-12-29T12:40:11.9647373Z ==> FAILED
```
https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=1824

**Comment by MikeMcQuaid** [comment]
@sjackman @jonchang `brew config` now reports `HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew` but yet this `brew doctor` check is failing on Linux. Can you help debug/fix this please?

**Comment by sjackman** [comment]
Based on the above error message `Warning: Your Homebrew's prefix is not /usr/local.` it appears that `Homebrew::DEFAULT_PREFIX` is `/usr/local` rather than the expected `/home/linuxbrew/.linuxbrew`. I can't replicate that issue locally.
```sh
$ brew --version
Homebrew 1.8.6-52-g5a32ebb
$ brew doctor
Your system is ready to brew.
$ brew irb <<<'Homebrew::DEFAULT_PREFIX'
…
"/home/linuxbrew/.linuxbrew"
```

I can take a look into it later this evening.

**Comment by sjackman** [comment]
I triggered a rebuild of this job on Azure.
https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=1831

**Comment by MikeMcQuaid** [comment]
Ah HOMEBREW_FORCE_HOMEBREW_ON_LINUX is set and shouldn’t be.

**Comment by jonchang** [comment]
```
==> Installing testbottest dependency: gcc
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.xz
==> Patching
patching file gcc/graphite.h
Error: An exception occurred within a child process:
  NameError: uninitialized constant OS::Mac::CLT
```

`OS::Mac::CLT` is not defined on Linux, but the Homebrew/core `gcc` formula uses it as a check to determine whether the bottle can be poured. I'm not sure why test-bot is reporting `Core tap ORIGIN: https://github.com/Homebrew/homebrew-core` instead of the Linuxbrew remote.

**Comment by jonchang** [comment]
Ok, the core tap origin should be Homebrew/core, but HOMEBREW_FORCE_HOMEBREW_ON_LINUX is set, brew pretends its on macOS. When it's not pretending, brew will implicitly bring in `gcc` and friends in `extend/os/linux/keg_relocate.rb`.

**Comment by jonchang** [comment]
One thing we could do is to to skip the brew doctor prefix check on Linux if `HOMEBREW_FORCE_HOMEBREW_ON_LINUX` is set, but maybe there's a cleaner solution.

**Comment by sjackman** [comment]
PR https://github.com/Homebrew/brew/pull/5454 should hopefully resolve this issue.
I suggest leaving `HOMEBREW_FORCE_HOMEBREW_ON_LINUX=1` defined to avoid installing `gcc`.

**Comment by MikeMcQuaid** [comment]
> 'm not sure why test-bot is reporting `Core tap ORIGIN: https://github.com/Homebrew/homebrew-core` instead of the Linuxbrew remote.

There's a few places where it's hardcoded to clone that. I've updated them now.

**Pull request merged**
