### PR TITLE
tests/formulae: downgrade optional steps to warnings

### PR DESCRIPTION
**Pull request by carlocab**
Some of the `brew fetch` and `brew install --only-dependencies` that we
do will be repeated if necessary when we `brew install` the formula
being tested.

Thus, it makes sense for failures of these steps to be warnings rather
than errors. This will help minimise the noise in CI runs where a `brew fetch`
failed but the actual build and test succeeded.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> This will help minimise the noise in CI runs where a `brew fetch`
> failed but the actual build and test succeeded.

How can the build succeed if the fetch failed?

**Comment by carlocab** [comment]
> How can the build succeed if the fetch failed?

`brew install` attempts another `fetch`.

**Comment by MikeMcQuaid** [comment]
> `brew install` attempts another `fetch`. You never actually need to do `brew fetch` -- it's only useful for caching, or for giving downloads a few extra chances to succeed in case they are flaky.

But `brew fetch` is retried multiple times. Couldn't we increase the number of retries further rather than relying on the `brew install` actually signalling the `brew fetch` failures?

**Comment by carlocab** [comment]
We could, but we probably want to retry with exponential backoff, since I think the delay between the `brew fetch` and `brew install` is what helps the fetch-during-install succeed.

**Comment by MikeMcQuaid** [comment]
> We could, but we probably want to retry with exponential backoff, since I think the delay between the `brew fetch` and `brew install` is what helps the fetch-during-install succeed.

Yeh, 👍🏻 to adding an exponential back-off into Homebrew/brew's retry logic 👍🏻

**Comment by carlocab** [comment]
Homebrew/brew#13807

**Comment by carlocab** [comment]
Here's an example of the kind of failures that I'd like to avoid (though it requires more changes to fix):

`brew install --only-dependencies root` failed [here](https://github.com/Homebrew/homebrew-core/actions/runs/3056643249/jobs/4931068480#step:10:222). However, all other steps (e.g. `brew install root`, `brew test root`, and `brew linkage --test root`) succeeded.

A failure of `brew install --only-dependencies` should not be failing CI.

**Comment by MikeMcQuaid** [comment]
> `brew install --only-dependencies root` failed [here](https://github.com/Homebrew/homebrew-core/actions/runs/3056643249/jobs/4931068480#step:10:222). However, all other steps (e.g. `brew install root`, `brew test root`, and `brew linkage --test root`) succeeded.

Possible solutions:
- add `brew fetch --only-dependencies` where we can use `--retry`
- automatically retry all downloads e.g. 1-2 times before failing

I think `brew install --only-dependencies root` failing _should_ fail CI but arguably it should not be failing when a retry fixes the issue. This seems like something that will affect end-users as much as test-bot.

**Pull request closed without merging**
