### PR TITLE
Use CoreTap.instance.default_remote

### PR DESCRIPTION
**Pull request by sjackman**
See https://github.com/Homebrew/brew/pull/5018#issuecomment-431689462

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@sjackman I'm not ready to have this happen yet until the projects are merged, sorry.

**Comment by sjackman** [comment]
Closed without merging.

**Comment by MikeMcQuaid** [comment]
@sjackman I'm happy for this to be left open until it makes sense to merge?

**Comment by MikeMcQuaid** [comment]
Done in https://github.com/Homebrew/homebrew-test-bot/pull/218!

**Pull request closed without merging**
