### PR TITLE
ci-upload: redact token in the log

### PR DESCRIPTION
**Pull request by xu-cheng**
Depends on https://github.com/Homebrew/brew/pull/6291

### CODE REVIEW

**Comment by xu-cheng** [comment]
This PR should also be merged. Noted due to the usage of `ENV.clear_sensitive_environment!`, we have to specify tokens here.

**Comment by MikeMcQuaid** [comment]
Cool, thanks @xu-cheng!

**Comment by sjackman** [comment]
Thank you, @xu-cheng !

**Comment by iMichka** [comment]
Thanks @xu-cheng !

**Pull request merged**
