### PR TITLE
lib/test: cleanup during build.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Ensure that every time we install a new formula or bottled dependent that we check the state of the disk usage and nuke HOMEBREW_CACHE if it has got too full.

### CODE REVIEW

**Comment by Bo98** [comment]
Interesting solution. I think this should work - I guess we'll soon find out!

I'm always cautious parsing command line output given there's likely edge cases (e.g. `/home`) but I think it will be ok for this. Shame that macOS doesn't have `--output=pcent`.

Does anything appear in the console log when this cleanup is triggered? Doesn't really matter - just interested.

**Comment by MikeMcQuaid** [comment]
> Interesting solution. I think this should work - I guess we'll soon find out!

Hah yup 😅 

> I'm always cautious parsing command line output given there's likely edge cases (e.g. `/home`) but I think it will be ok for this. Shame that macOS doesn't have `--output=pcent`.

Yeh, I also looked for a better solution.

> Does anything appear in the console log when this cleanup is triggered? Doesn't really matter - just interested.

It wouldn't so I've added a `test "brew", "cleanup", "--prune=0"` before the `HOMEBREW_CACHE.children.each(&:rmtree)`. That'll mean the `==> brew cleanup --prune=0` will show up in the logs much in the same way `==> brew cleanup --prune=3` shows up currently at the end.

Let me know after this is merged if it seems sufficient or not. We could also consider clearing e.g. installed formulae and/or `/tmp` if necessary.

**Comment by Bo98** [comment]
> Let me know after this is merged if it seems sufficient or not. We could also consider clearing e.g. installed formulae and/or `/tmp` if necessary.

Will do. :+1:

**Comment by iMichka** [comment]
Let's try this :)

**Pull request merged**
