### PR TITLE
lib/tests/formulae.rb: specify --formula in 'brew list'

### PR DESCRIPTION
**Pull request by Akylzhan**
Required for https://github.com/Homebrew/brew/pull/8851

### CODE REVIEW

**Comment by Akylzhan** [comment]
Hm, I have thought that it is not TTY and test-bot failed since I use `odeprecated` to tell that '--formula' should be specified. And when I commented line with `odeprecated`, test-bot doesn't throw errors

**Comment by MikeMcQuaid** [comment]
Can you elaborate where you're seeing this?

**Comment by Akylzhan** [comment]
https://github.com/Akylzhan/brew/blob/9b9bb7d3d383c578416d6f6d0113964ebd92ca8a/Library/Homebrew/cmd/list.rb#L90

**Comment by MikeMcQuaid** [comment]
Sorry, can you link to a failing CI check?

**Comment by Akylzhan** [comment]
https://github.com/Homebrew/brew/pull/8851/checks?check_run_id=1227898156

**Comment by Akylzhan** [comment]
Are there any updates? @MikeMcQuaid. Or I don't get something and the PR is not needed?

**Comment by MikeMcQuaid** [comment]
Sorry for the delay, merged @Akylzhan, thanks!

**Pull request merged**
