### PR TITLE
Use `module_function`.

### PR DESCRIPTION
**Pull request by reitermarkus**
Needed for https://github.com/Homebrew/brew/pull/1145.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Can you explain this a bit; not sure I understand?

**Comment by MikeMcQuaid** [comment]
@reitermarkus Think this should be good to 🚢 too?

**Comment by reitermarkus** [comment]
Yes. 👍

**Comment by MikeMcQuaid** [comment]
@reitermarkus If you felt like doing the same thing for homebrew-bundle and homebrew-services that'd be 💟

**Comment by reitermarkus** [comment]
None of them use `module Homebrew`, so should be good.

**Comment by MikeMcQuaid** [comment]
@reitermarkus 🆒 thanks.

**Pull request merged**
