### PR TITLE
Check for untapped deps when sorting formulae

### PR DESCRIPTION
**Pull request by scpeters**
I maintain at least one formula with cross-tap dependencies ([osrf/simulation/gazebo7](https://github.com/osrf/homebrew-simulation/blob/master/gazebo7.rb#L29) depends on `cartr/qt4/qt@4`). In #91, I fixed a bug in `unlink_conflicts` related to this use case that rescues from `TapFormulaUnavailableError`, adds the missing tap, and tries again to call `recursive_dependencies` on a formula.

I just noticed there is an earlier place where a missing tap causes a problem: in the `run` function, a [formulae.each loop](https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L1105-L1111) is right after `homebrew`. 
The `formulae` function [calls brew deps](https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L1080) and then sorts the formulae so the lowest level dependencies are processed first, but `brew deps` fails if untapped formulae aren't available:

~~~
$ brew deps gazebo7 && echo success
Error: No available formula with the name "cartr/qt4/qt@4" 
Please tap it and then try again: brew tap cartr/qt4
$
~~~

I hadn't noticed this before when just building a gazebo7 bottle, but I now notice that the order is wrong when trying to build bottles for https://github.com/osrf/homebrew-simulation/pull/269, which has bumped revisions for `gazebo7` and two of its dependencies that are later in the alphabet, so it [builds out of order](https://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder-elcapitan/64/console).

This PR checks `$?` to see if the `brew deps` command failed, and if so calls `Formulary.factory(formula).recursive_dependencies` with a `rescue` block to add the missing tap. I put WIP in the title because it feels messy to duplicate code from #91. I am assuming that `brew deps` behavior should not change to automatically add missing taps.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Seems reasonable, thanks @scpeters. @ilovezfs any thoughts?

**Comment by scpeters** [comment]
I removed `WIP` from the title because I think it's ready for review.

**Comment by scpeters** [comment]
I just reconfirmed the bug and fix with https://github.com/osrf/homebrew-simulation/pull/372

**Comment by MikeMcQuaid** [comment]
Thanks again @scpeters!

**Pull request merged**
