### PR TITLE
test_formulae: delay requiring `utils/github/artifacts`

### PR DESCRIPTION
**Pull request by carlocab**
Fixes

    Error: cannot load such file -- utils/github/artifacts

https://github.com/MikeMcQuaid/strap/actions/runs/5153221949/jobs/9282422805?pr=782#step:3:8

### CODE REVIEW

**Comment by Bo98** [comment]
Have we ever supported test-bot on old versions of Homebrew? We very routinely add new flags etc in Homebrew and use them here immediately (#920, #887, etc.).

**Comment by carlocab** [comment]
🤷 Maybe not, but it's a tiny change so I don't mind carrying it for a bit.

**Review by Bo98 — APPROVED** [review]

**Comment by Bo98** [comment]
It gets a bit complicated because GitHub runner images roll out over a period of time (and potentially even separate times across macos-11, 12 & 13). e.g. 14% of repositories use macos-13 20230524.1, while others use 20230509.4.

**Comment by MikeMcQuaid** [comment]
Thanks @carlocab!

**Pull request merged**
