### PR TITLE
lib/step: sleep after encountering msgpack `LoadError` on macOS 15

### PR DESCRIPTION
**Pull request by carlocab**
We're encountering intermittent `LoadError`s for msgpack on macOS 15.
It's not clear how to reproduce these errors, so let's sleep for an hour
when we see this to give @Bo98 the chance to log in and investigate.

### CODE REVIEW

**Review by Bo98 — APPROVED** [review]
LGTM though technically should also gate on either Homebrew/core or maybe `GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED` in case there's third-party taps already running macOS 15.

**Comment by carlocab** [comment]
I wonder if we can get `test-bot` to post a comment at https://github.com/Homebrew/homebrew-core/issues/184132 directly.

**Comment by carlocab** [comment]
> LGTM though technically should also gate on either Homebrew/core or maybe `GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED` in case there's third-party taps already running macOS 15.

Scoped this to Homebrew-owned repos.

**Comment by carlocab** [comment]
Hooked our first one! https://github.com/Homebrew/homebrew-core/actions/runs/10796054456/job/29944157474 🎣

**Pull request merged**
