### PR TITLE
test_bot: restrict CLI arguments.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Accept only formula, `HEAD` or GitHub Actions commits for building.

I believe other functionality is unused. If I'm wrong: correct me.

### CODE REVIEW

**Comment by scpeters** [comment]
we have been passing a URL to test-bot to build bottles in our tap, but I'll try to look into the most recent changes to see if we can do it differently

**Comment by MikeMcQuaid** [comment]
@scpeters Sorry to hear that. Your best bet will be trying to set the `diff_start_sha1` and `diff_end_sha1` some other way (perhaps by faking the GitHub Actions environment variables).

What CI provider are you using? I'd recommend a move to GitHub Actions for the easiest `test-bot` usage. Give me a shout in Slack if you want to talk more about this.

**Comment by scpeters** [comment]
we have our own custom jenkins instance

I will indeed look into using GitHub actions instead and reach out if I have questions

**Comment by MikeMcQuaid** [comment]
> we have our own custom jenkins instance

👍 cool. 



> I will indeed look into using GitHub actions instead

Yeh, we found it one less server to run. You can probably steal a bunch from homebrew-core's workflow files at this point that are running on our self-hosted Actions workers.

**Pull request merged**
